# https://github.com/mmistakes/minimal-mistakes/blob/master/_config.yml

# Theme settings
#remote_theme: mmistakes/minimal-mistakes@4.19.1
#minimal_mistakes_skin: # air, aqua, contrast, dark, dirt, neon, mint, plum, sunrise

# Site settings
title: Směnárna Kurzy

theme: jekyll-theme-slate
